Universidad/Controllers/UniversidadController.cs
using Universidad.Context;
using Universidad.Context.Dao;
using Universidad.Models;
using Universidad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Universidad.Controllers
{
    public class UniversidadController : Controller
    {
        Contexto contexto;
        public UniversidadController()
        {
            contexto = new Contexto();
        }

        // GET: Universidad
        public ActionResult Index(string mensaje)
        {
            ViewBag.Mensaje = mensaje;
            //Devuelve el model
            return View(new EstudianteDao(contexto).ToSelectForIndex());
        }

        // GET: Universidad/Details/5
        public ActionResult Detalles(long? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var estudiante = contexto.Estudiante.FirstOrDefault(x => x.Id == id.Value);
                if (estudiante == null)
                    return RedirectToAction("Index");
                else
                    return View(estudiante);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Universidad/Crear un nuevo estudiante
        public ActionResult Create(long? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var estudiante = contexto.Estudiante.FirstOrDefault(x => x.Id == id.Value);
                if (estudiante == null)
                    return RedirectToAction("Index");
                else
                    return View(estudiante);
            }
            return View();
        }
        //CREAR Y EDITAR
        //// Envia POST: Universidad/Crear un nuevo estudiante
        //[HttpPost]
        //public ActionResult Create(Estudiante estudiante)
        //{
        //    if (estudiante.Id > 0)
        //    {
        //        var estudianteU = contexto.Estudiante.FirstOrDefault(x => x.Id == estudiante.Id);
        //        estudianteU.Nombre = estudiante.Nombre;
        //        estudianteU.FechaNacimiento = estudiante.FechaNacimiento;
        //        estudianteU.Domicilio = estudiante.Domicilio;
        //        contexto.SaveChanges();
        //        return RedirectToAction("Index", new { mensaje = "Actualizado" });
        //    }
        //    contexto.Estudiante.Add(estudiante);
        //    contexto.SaveChanges();

        //    return RedirectToAction("Index", new { mensaje = "Guardo correctamente" });
        //}

        // Envia POST: Universidad/Crear un nuevo estudiante
        [HttpPost]
        public ActionResult Create(Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                var estudianteU = contexto.Estudiante.FirstOrDefault(x => x.Id == estudiante.Id);
                estudianteU.Nombre = estudiante.Nombre;
                estudianteU.FechaNacimiento = estudiante.FechaNacimiento;
                estudianteU.Domicilio = estudiante.Domicilio;
                contexto.Estudiante.Add(estudiante);
                contexto.SaveChanges();

                return RedirectToAction("Index", new { mensaje = "Guardo correctamente" });
            }
            return View(estudiante);
        }

        public ActionResult Editar(long? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var estudiante = contexto.Estudiante.FirstOrDefault(x => x.Id == id.Value);
                if (estudiante == null)
                    return RedirectToAction("Index");
                else
                    return View(estudiante);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Editar(Estudiante estudiante)
        {
            var estudianteU = contexto.Estudiante.FirstOrDefault(x => x.Id == estudiante.Id);
            estudianteU.Nombre = estudiante.Nombre;
            estudianteU.FechaNacimiento = estudiante.FechaNacimiento;
            estudianteU.Domicilio = estudiante.Domicilio;
            contexto.SaveChanges();

            return RedirectToAction("Index", new { mensaje = "Actualizado" });

        }

        // POST: Universidad/Delete/5
        [HttpPost]
        public ActionResult Delete(long? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var estudianteU = contexto.Estudiante.FirstOrDefault(x => x.Id == id.Value);
                if (estudianteU == null)
                    return RedirectToAction("Index", new { mensaje = "Estudiante no encontrado" });
                contexto.Estudiante.Remove(estudianteU);
                contexto.SaveChanges();
                return RedirectToAction("Index", new { mensaje = "Estudiante eliminado" });
            }
            return RedirectToAction("Index", new { mensaje = "Estudiante no encontrado" });
        }

        public ActionResult ENoEncotrado(long id)
        {
            ViewBag.Id = id;
            return View();
        }


        //[HttpGet]
        //[AllowAnonymous]
        //public JsonResult GetString()
        //{
        //    var dataTablesResult = new DataTablesResult();
        //    dataTablesResult.draw = 1;
        //    dataTablesResult.recordsTotal = 1000;
        //    dataTablesResult.recordsFiltered = 1000;
        //    dataTablesResult.data.AddRange(contexto.Estudiante.ToList());
        //    return Json(dataTablesResult, JsonRequestBehavior.AllowGet);
        //}

        [HttpGet]
        [AllowAnonymous]
        public JsonResult GetEstudiante(int draw, int start, int length)
        {
            var total = contexto.Estudiante.Count();

            var dataTablesResult = new DataTablesResult();
            dataTablesResult.draw = draw;
            dataTablesResult.recordsTotal = total;
            dataTablesResult.recordsFiltered = total;
            var EstudianteM = contexto.Estudiante.OrderBy(x => x.Id).Skip(start).Take(length).Select(e => new { Nombre = e.Nombre, FechaNacimiento = e.FechaNacimiento.ToString(), Domicilio = e.Domicilio, Id = e.Id }).ToList();

            //usuarioMostrar.ForEach(e =>
            //{
            //    e.DT_RowId = "row_" + e.Id;
            //    e.DT_RowData = new DT_RowData { pKey = (int)e.Id };
            //});
            dataTablesResult.data.AddRange(EstudianteM);
            return Json(dataTablesResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Universidad/Views/Universidad/Create.cshtml
@model Universidad.Models.Estudiante

@section styles{
    <!--ESTILOS SELECT BOOSTRAPT-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
}<br />
<h2 style="text-align: center">NUEVO ESTUDIANTE</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-1">
        <a type="button" class="btn btn-outline-info" href='@Url.Action("Index", "Universidad")'><i class="fas fa-caret-square-left"></i> REGRESAR</a>
    </div>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-sm-5">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-5">
            &emsp;<label>Fecha de Nacimiento</label>
            @Html.TextBoxFor(model => Model.FechaNacimiento, new { @class = "form-control", @type = "date", @Value = Model?.FechaNacimiento.ToString("dd-MM-yyyy") })
            @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-5">
            @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.Domicilio, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-outline-secondary" />
        </div>
    </div>
}
@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>
}

Universidad/Views/Universidad/Detalles.cshtml
@model Universidad.Models.Estudiante

<div class="col-md-11">
    <br />
    <h2 style="text-align: center">DATOS DEL ESTUDIANTE @ViewBag.Id</h2>
    <hr style="width:70%; height: 8px; color:darkred" />
</div><br />
<div class="col-md-1">
    <a type="button" class="btn btn-outline-info" href='@Url.Action("Index", "Universidad")'><i class="fas fa-caret-square-left"></i> REGRESAR</a>
</div><br />
@Html.AntiForgeryToken()
<div class="jumbotron">
    <div style="text-align: center">
        <dl>
            <dt>Nombre</dt>
            <dd>@Model.Nombre</dd>
            <dt>Fecha de Nacimiento</dt>
            <dd>@Model.FechaNacimiento.ToString("dd-MM-yyyy")</dd>
            <dt>Domicilio</dt>
            <dd>@Model.Domicilio</dd>
        </dl>
        <div style="text-align: center">
            <a class="btn btn-light" href='@Url.Action("Editar","Universidad", new {Id = @Model.Id })'><i class="far fa-edit"></i> Editar</a>
        </div>
    </div>
</div>
<form action='@Url.Action("Delete","Universidad" )' method="post">
    <input type="hidden" name="Id" value="@Model.Id" />
    <button type="submit" class="btn btn-danger"><i class="fas fa-user-times"></i> Eliminar</button>
</form>

Universidad/Views/Universidad/Index.cshtml
@*@model List<Universidad.ViewModels.EstudiantViewModels>*@
@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
}
<div class="row">

    <div class="col-md-10" style="text-align: center">
        <br />
        <h2>ESTUDIANTES</h2>
        <hr style="width:70%; height: 8px; color:darkred" />
    </div>
    <div class="col-md-2">
        <br />
        <a class="btn btn-outline-secondary" href='@Url.Action("Create","Universidad")'><i class="far fa-address-card"></i>  Agregar</a>
    </div>
</div>
<br />
@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-info">
        @ViewBag.Mensaje
    </div>
}
<br />
<table class="table table-striped table-bordered" id="Universidad">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>FECHA DE NACIMINETO</th>
            <th>DOMICILIO</th>
            <th>OPCIONES</th>
        </tr>
    </thead>
    @*@foreach (var estudiante in Model)
            {
        <tr>
            <td>@estudiante.Nombre</td>
            <td>@estudiante.FechaNacimiento.ToString("dd-MM-yyyy")</td>
            <td>@estudiante.Domicilio</td>
            <td>
                <a class="btn btn-light" href='@Url.Action("Detalles","Universidad", new { Id = estudiante.Id })'><i class='far fa-user'></i> Ver</a>
            </td>
        </tr>
            }*@

</table>
@section scripts{
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script>
        //function FormatoFecha(o) {
        //    return o.value &&
        //        Y.DataTime.Date.format(o.value, { format: "MM/dd/YYYY" });
        //}

        $(document).ready(function () {
            $('#Universidad').DataTable({
                "processing": true,
                serverSide: true,
                aLengthMenu: [2,4,5],
                ajax: '/Universidad/GetEstudiante',
               columns: [
                   { "data": "Nombre" },
                   { "data": "FechaNacimiento"/*formatter: FormatoFecha*/},
                   { "data": "Domicilio" },
                   { "render": function (data, type, full, meta)
                     { return '<a class="btn btn-light" href="/Universidad/Detalles/' + full.Id + '"><i class="far fa-user"></i> Ver</a>'; },
                   },
               ],
            });
        });
    </script>
}