UWeb/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UDataLayer.Context;
using UDataLayer.Context.Manager;
using UDataLayer.Context.Orm;

namespace WebApplication1.Controllers
{
    public class EstudianteController : Controller
    {
        Contexto contexto;
        public EstudianteController()
        {
            contexto = new Contexto();
        }



        // GET: Estudiante Index
        public ActionResult Index(string mensaje)
        {
            ViewBag.Mensaje = mensaje;
            return View(new UManager(contexto).ToSelectAll());
        }
        
        //public ActionResult Detalles(Guid? Id)
        //{
        //    if (Id.HasValue != null)
        //    {
        //        var estudiante = contexto.Estudiante.FirstOrDefault(x => x.Id == Id.HasValue);
        //        if (estudiante == null)
        //            return RedirectToAction("Index");
        //        else
        //            return View(estudiante);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index");
        //    }
        //}

        //[HttpPost]
        //public ActionResult Create(Estudiante estudiante)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var estudianteU = contexto.Estudiante.FirstOrDefault(x => x.Id == estudiante.Id);
        //        contexto.Estudiante.Add(estudiante);
        //        contexto.SaveChanges();

        //        return RedirectToAction("Index", new { mensaje = "Guardo correctamente" });
        //    }
        //    return View(estudiante);
        //}
    }
}

UWeb/Controllers/GradoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UDataLayer.Context;
using UDataLayer.Context.Manager;

namespace WebApplication1.Controllers
{
    public class GradoController : Controller
    {
        Contexto contexto;
        public GradoController()
        {
            contexto = new Contexto();
        }
        
        
        // GET: Grado
        public ActionResult Index(string mensaje)
        {
            ViewBag.Mensaje = mensaje;
            return View(new UManager(contexto).SelesctGrado());
        }
    }
}

UWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UWeb/Views/Estudiante/Index.cshtml
@model IEnumerable<UDataLayer.Context.Orm.Estudiante>
@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    }
    <div class="row">
        <div class="col-md-10" style="text-align: center">
            <br />
            <h2>ESTUDIANTES</h2>
            <hr style="width:70%; height: 8px; color:darkred" />
        </div>
        <div class="col-md-2">
            <br />
            <a class="btn btn-outline-secondary" href='@Url.Action("Create","Universidad")'><i class="far fa-address-card"></i>  Agregar</a>
        </div>
    </div>

    @if (ViewBag.Mensaje != null)
    {
        <div class="alert alert-info">
            @ViewBag.Mensaje
        </div>
    }

    <br />
    <table class="table">
        <tr>
            <th>NOMBRE</th>
            <th>FECHA DE NACIMIENTO</th>
            <th>DOMICILIO</th>
            <th>OPCIONES</th>
        </tr>

        @foreach (var e in Model)
        {
            <tr>
                <td>
                    @e.Nombre
                </td>
                <td>
                    @e.FechaNacimiento
                </td>
                <td>
                    @e.Domicilio
                </td>

                <td>
                    <a class="btn btn-light" href='@Url.Action("Detalles","Universidad", new { Id = e.Id })'><i class='far fa-user'></i> Ver</a>
                </td>
            </tr>
        }

    </table>

UWeb/Views/Grado/Index.cshtml
@model IEnumerable<UDataLayer.Context.Orm.Grado>

@{
    ViewBag.Title = "Index";
}
@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
}
<div class="row">

    <div class="col-md-10" style="text-align: center">
        <br />
        <h2>SEMESTRE</h2>
        <hr style="width:70%; height: 8px; color:darkred" />
    </div>
    <div class="col-md-2">
        <br />
        <a class="btn btn-outline-secondary" href='@Url.Action("Create","Universidad")'><i class="far fa-list-alt"></i>  Agregar</a>
    </div>
</div>
<br />
@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-info">
        @ViewBag.Mensaje
    </div>
}
<br />
<table class="table">
    <tr>
        <th>SEMESTRE</th>
        <th>OPCIONES</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Semestre
            </td>
            <td>
                <a class="btn btn-light" href='@Url.Action("Detalles","Universidad", new { Id = item.Id })'><i class="far fa-calendar-alt"></i> Ver</a>
            </td>
        </tr>
    }

</table>

UWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<br/>
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<br/>
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>

    <br />
    <div id="gridEstudiante"></div>
    <h1>Estudiante seleccionado</h1>
    <p>
        Nombre Estudiante<span id="NombreEstudiante"></span><br />
        Grado<span id="Grado"></span><br />
    </p>

</div>


@section scripts{
    
    <script>
        $("#gridEstudiante").dxSelectBox({
            dataSource: "http://localhost:/51484/Api/Estudiante",
            displayExpr: 'Combo',
            onClick: function (e) {
                $('#NombreEstudiante').html(e.estData.Nombre);
            }
        });

    </script>
}

UWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/app.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="~/Content/dx.light.css" rel="stylesheet" />
    <link href="~/Content/dx.common.css" rel="stylesheet" />
    @RenderSection("styles", false)
    <title>@ViewBag.Title - Universidad</title>
</head>
<body>
    <div class="nav">
        <div class="logo">
            <img src="~/Imag/UV.png" />
            <i style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">UNIVERSIDAD</i>
        </div>
        <div class="main-nav">
            <a class="hamburger-nav"></a>
            <ul class="menu">
                <li>
                    <a href='@Url.Action("Index", "Home")'><i class="fa fa-home"></i> INICIO</a>
                </li>
                <li>
                    <a href='@Url.Action("Index", "Estudiante")'><i class="fa fa-file-image-o"></i> Estudiantes</a>
                </li>
                <li>
                    <a href='@Url.Action("Index", "Grado")'><i class="far fa-list-alt"></i> Semestre</a>
                </li>
                <li>
                    <a href='@Url.Action("Contact", "Home")'><i class="fa fa-envelope"></i> Contact</a>
                </li>
                <li>
                    <a href=@Url.Action("About", "Home")><i class="fa fa-cogs"></i> Settings</a>
                </li>
            </ul>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()

    </div>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.1.0.min.js"></script>
    <script src="~/Scripts/dx.web.js"></script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/app.js"></script>

</body>
</html>